
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma


Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/seeds/*'
