
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Lint/RedundantWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - "app/services/geometry/*.rb"

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "app/services/geometry/*.rb"

Metrics/PerceivedComplexity:
  Exclude:
    - "app/services/geometry/*.rb"

Naming/VariableNumber:
  Exclude:
    - "app/services/geometry/*.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/services/geometry/*.rb"

Metrics/AbcSize:
  Exclude:
    - "app/services/geometry/*.rb"

Naming/UncommunicativeMethodParamName:
  Exclude:
    - "app/services/geometry/*.rb"

Metrics/BlockLength:
  Exclude:
    - "app/controllers/api/**/*.rb"
    - "app/services/geometry/*.rb"
    - "spec/**/*.rb"

AllCops:
  Exclude:
    - "config/**/*"
    - "bin/**/*"
    - "db/migrate/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/seeds/*"
